// const { createSlice } = require("@reduxjs/toolkit");

// const tourSlice = createSlice({
//     name: 'tour',
//     initialState:{
//         token: '',
//         loginStatus: false,
//         userId: "0"
//     },
//     reducers:{
//         addToken: (state, action) =>{
//             state.token = action.payload;
//         },
//         addLoginStatus: (state, action) =>{
//             console.log('action',action.payload);
//             state.loginStatus = action.payload;
//         },
//         addUserId: (state, action) =>{
//             // console.log('action',action.payload);
//             state.userId = action.payload;
//         }

//     }
// })

// export const { addToken, addLoginStatus, addUserId } = tourSlice.actions;

// export default tourSlice.reducer;

// counterSlice.js
import { createSlice } from "@reduxjs/toolkit";

const tourSlice = createSlice({
  name: "tour",
  initialState: {
    token: "",
    loginStatus: false,
    userId: "0",
    user: {}
  },
  reducers: {
    addToken: (state, action) => {
      console.log("token action", action.payload);
      state.token = action.payload;
    },
    addLoginStatus: (state, action) => {
      console.log("login action", action.payload);
      state.loginStatus = action.payload;
    },
    addUserId: (state, action) => {
      // console.log('action',action.payload);
      state.userId = action.payload;
    },
    addUser: (state, action) => {
      // console.log('action',action.payload);
      state.user = {...action.payload};
    }
  },
});

// Export the action creators generated by createSlice
export const { addLoginStatus, addToken, addUserId, addUser, logout } = tourSlice.actions;

// Export the reducer function
export default tourSlice.reducer;
